FROM apache/airflow:2.3.3

USER airflow

RUN pip install psycopg2
RUN pip install requests
RUN pip install json
RUN pip install pandas
RUN pip install datetime
RUN pip install sqlalchemy 
RUN pip install smtplib
RUN pip install email.message